### PR TITLE
Allow for customisation and allow for floating point widths

### PR DESCRIPTION
**Pull request by ccgdesigns**
- Allowed for custom classes on parent div
- Fixed the layout when width of elements is not an int (percentage based layouts typically)

### CODE REVIEW

**Comment by borntorun** [comment]
Hi, I think that attribute 'parentClass' will break actual implementations; it should not be required.

**Comment by ccgdesigns** [comment]
yep you're right sorry (I've updated my fork https://github.com/ccgdesigns/angular-dynamic-layout/commit/8e51a8543032f3a4a14e146e5fd33bcb94ce30cd ), Im not sure if this feature is useful to any one else tbh. Perhaps only the floating point size change is worth merging (sorry I should have really split this into two commits)

**Comment by tristanguigue** [comment]
Hi, thank you for your contribution, that'd be great if you can do 2 PRs indeed. Also the diff contains changes introduced (and merged) in https://github.com/tristanguigue/angular-dynamic-layout/pull/7 somehow.
- For the parent class, do you have an example where it's needed?
- For the width, I'd gladly merge that fix

**Comment by intellix** [comment]
I've incorporated the width improvements into #9

**Pull request closed without merging**
